### ISSUE TITLE
Can't apply global styles to <i-feather> component

### ISSUE THREAD

**Issue by TheLordDrake** [michaelbazos/angular-feather#22]
Because the `<i-feather>` component applies default styling, you cannot apply a global style to icons. Styles have to be applied locally, which is redundant if attempting to provide common style details to all icons in the application. For example, if I want all icons to be 50x50, I must create a component level class for each component using an icon.

Is there a suggested work around for this?

**Comment by michaelbazos** [comment]
@TheLordDrake 

It's possible to take precedence over the existing inline styles of <i-feather> with the `!important` keyword:

```css
i-feather {
  height: 50px !important;
  width: 50px !important;
}
```

Alternatively, since all svg elements of the library have the `feather` css class you can also do that:

```css
.feather {
  height: 50px;
  width: 50px;
}
```

The svg element is under i-feather and has no inline width or height on it, so in this case no need for `!important`.

In addition, svg elements also have an `feather-{name}` class, so you can target specific icons if you need:

```css
.feather {
  height: 50px;
  width: 50px;
}

.feather-heart {
  color: red;
}
```

Let me know if this answers your question.
